import { Metadata } from "next"

export const metadata: Metadata = {
	title: 'Call',
	description: 'Generated by create next app',
}



export default function CallPage() {
	return (
		<div>CallPage</div>
	)
}