import type { Metadata } from "next";

export const metadata: Metadata = {
	title: 'Friends',
	description: 'Generated by create next app',
}

export default function FriendsPage() {
	return <div>Friends page</div>
} 