import type { Metadata } from "next";

export const metadata: Metadata = {
	title: 'Setti ngs',
	description: 'Generated by create next app',
}

export default function SettingsPage() {
	return <div>Settings page</div>
}